# Generated by Django 4.1.6 on 2023-03-01 08:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0037_auto_20210125_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PROCESSED', 'Необработан'), ('COMPLETED', 'Завершен')], default='PROCESSED', max_length=9, verbose_name='статус заказа')),
                ('payment', models.CharField(choices=[('CARD', 'Электронно'), ('CASH', 'Наличные')], default='CASH', max_length=4, verbose_name='способ оплаты')),
                ('firstname', models.CharField(max_length=20, verbose_name='имя')),
                ('lastname', models.CharField(max_length=20, verbose_name='фамилия')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='телефон')),
                ('address', models.CharField(max_length=128, verbose_name='адрес доставки')),
                ('comment', models.TextField(blank=True, max_length=250, verbose_name='комментарий')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('called', models.DateTimeField(blank=True, null=True, verbose_name='звонок клиенту')),
                ('completed', models.DateTimeField(blank=True, null=True, verbose_name='доставлен')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='RestaurantOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(verbose_name='расстояние')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.order', verbose_name='заказ')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='foodcartapp.restaurant', verbose_name='ресторан')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='foodcartapp.order', verbose_name='заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='foodcartapp.product', verbose_name='наименование')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['phonenumber', 'firstname', 'lastname', 'address', 'status', 'called', 'completed', 'payment'], name='foodcartapp_phonenu_d18295_idx'),
        ),
    ]
