# Generated by Django 4.1.6 on 2023-03-01 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order_restaurantorder_productorder_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantorder',
            options={'verbose_name': 'ресторан готовящий заказ', 'verbose_name_plural': 'рестораны готовящие заказ'},
        ),
    ]
