# Generated by Django 4.1.6 on 2023-03-01 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_alter_restaurantorder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Необработан'), ('PROCESSED', 'Готовится'), ('COMPLETED', 'Завершен')], default='WAITING', max_length=9, verbose_name='статус заказа'),
        ),
        migrations.AlterField(
            model_name='restaurantorder',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restaurants', to='foodcartapp.restaurant', verbose_name='ресторан'),
        ),
    ]
