# Generated by Django 4.1.6 on 2023-02-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_alter_order_last_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='foodcartapp_phone_80de09_idx',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='phonenumber',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['phonenumber', 'firstname', 'lastname', 'address'], name='foodcartapp_phonenu_20ef54_idx'),
        ),
    ]
