# Generated by Django 4.1.6 on 2023-02-17 02:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_remove_order_foodcartapp_phone_80de09_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена'),
        ),
    ]
