# Generated by Django 4.1.6 on 2023-03-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20230219_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CARD', 'Электронно'), ('CASH', 'Наличные')], max_length=4, verbose_name='способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Необработан'), ('PROCESSING', 'Готовится'), ('COMPLETED', 'Завершен')], default='WAITING', max_length=10, verbose_name='статус заказа'),
        ),
    ]
