# Generated by Django 4.1.6 on 2023-03-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_alter_order_payment_alter_order_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='foodcartapp_phonenu_6b5d7a_idx',
            old_name='foodcartapp_phonenu_d18295_idx',
        ),
    ]
