# Generated by Django 4.1.6 on 2023-02-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_order_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='foodcartapp_phonenu_20ef54_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROCESSED', 'Необработан'), ('PROCESSED', 'Завершен')], default='PROCESSED', max_length=9, verbose_name='статус заказа'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['phonenumber', 'firstname', 'lastname', 'address', 'status'], name='foodcartapp_phonenu_ea3b7f_idx'),
        ),
    ]
