# Generated by Django 4.1.6 on 2023-03-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_rename_foodcartapp_phonenu_d18295_idx_foodcartapp_phonenu_6b5d7a_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='foodcartapp_phonenu_6b5d7a_idx',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='called',
            new_name='called_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='completed',
            new_name='completed_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['phonenumber', 'firstname', 'lastname', 'address', 'status', 'called_at', 'completed_at', 'payment'], name='foodcartapp_phonenu_6b5d7a_idx'),
        ),
    ]
