# Generated by Django 4.1.6 on 2023-02-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_remove_order_foodcartapp_phonenu_20ef54_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROCESSED', 'Необработан'), ('COMPLETED', 'Завершен')], default='PROCESSED', max_length=9, verbose_name='статус заказа'),
        ),
    ]
