# Generated by Django 4.1.6 on 2023-02-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=250, verbose_name='комментарий'),
        ),
    ]
