# Generated by Django 4.1.6 on 2023-03-06 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_alter_restaurantorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_no', to='foodcartapp.order', verbose_name='заказ'),
        ),
    ]
