# Generated by Django 4.1.6 on 2023-02-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_remove_order_foodcartapp_phonenu_ea3b7f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CARD', 'Электронно'), ('CASH', 'Наличные')], default='CASH', max_length=4, verbose_name='способ оплаты'),
        ),
    ]
