# Generated by Django 4.1.6 on 2023-03-07 03:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_alter_productorder_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=8, validators=[django.core.validators.MinValueValidator(100)], verbose_name='цена'),
        ),
    ]
