# Generated by Django 4.1.6 on 2023-02-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_order_payment'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='foodcartapp_phonenu_ac1af6_idx',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['phonenumber', 'firstname', 'lastname', 'address', 'status', 'called', 'completed', 'payment'], name='foodcartapp_phonenu_d18295_idx'),
        ),
    ]
