# Generated by Django 4.1.6 on 2023-03-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_alter_restaurantorder_distance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductOrder',
            new_name='OrderItem',
        ),
    ]
