# Generated by Django 4.1.6 on 2023-03-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, choices=[('CARD', 'Электронно'), ('CASH', 'Наличные')], db_index=True, max_length=4, verbose_name='способ оплаты'),
        ),
    ]
