# Generated by Django 4.1.6 on 2023-03-09 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantorder',
            name='distance',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='расстояние'),
        ),
    ]
