# This is a basic workflow to help you get started with Actions

name: Rollbar

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Notify deploy to Rollbar
        uses: rollbar/github-deploy-action@2.1.1
        id: rollbar_deploy
        with:
          environment: 'production'
          version: ${{ github.sha }}
        env:
          ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBARSERVER }}
          ROLLBAR_USERNAME: ${{ github.actor }}

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

#       - name: Rollbar deploy
#   # You may pin to the exact commit or the version.
#         uses: rollbar/github-undeployed-action@2.1.1
# #         uses: rollbar/github-deploy-action@2.1.1/
#         env:
#             ROLLBAR_ACCESS_TOKEN: ${{secrets.ROLLBARSERVER}}
#             ROLLBAR_USERNAME: 'spawlov'
#         with:
#           # Environment where your code is running. e.g. production
#           environment: 'production'
#           # Version deployed
#           version: ${{github.sha}}
